### ISSUE TITLE
after version 2.8.0 devices without webcam are not able create/join rooms

### ISSUE THREAD

**Issue by syamgk** [OpenVidu/openvidu-call#26]
​below is the error log form web-console:

```
message: NotAllowedError: The request is not allowed by the user agent or the platform in the current context.
name: "DEVICE_ACCESS_DENIED"
stack: 
​
```
How to replicate the issue?
For disabling webcam on Linux machines: 
`modprobe -r uvcvideo`
then go to https://demos.openvidu.io/openvidu-call/# from any browser and try creating a room

**Comment by drcursor** [comment]
Any news / possible workarounds ?

**Comment by CSantosM** [comment]
Hi, 

We'll get better OpenVidu Call and will fix this issue checking the videodevice when the app start.

**Comment by micaelgallego** [comment]
It is planned to publish a new version of OpenVidu Call the next week. Please stay tuned.

**Comment by drcursor** [comment]
I honestly would be glad with a workaround for the specific bug, if you are not able to publish this week.

**Comment by micaelgallego** [comment]
@CSantosM, do you know a quick change in the source code to allow non-camera users?

**Comment by CSantosM** [comment]
Hi, 
Actually it's not fix a bug, it's basically develop a new feature so we're not looking for a workaround.
To allow users without videoinput you have to check if the user has videoinputs availables.
If not, you can initialize the publisher setting to `false` the videosource property field of the OV.initPublisher method.
Then you only have to fix the tons of errors will appear in the angular app because the user won't has video. 
Once you fix it, all done.

**Comment by micaelgallego** [comment]
Thanks!
